/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.17.0-alpha.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/server";
import type * as addCart from "../addCart";
import type * as getCart from "../getCart";
import type * as getItems from "../getItems";
import type * as removeCart from "../removeCart";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: ApiFromModules<{
  addCart: typeof addCart;
  getCart: typeof getCart;
  getItems: typeof getItems;
  removeCart: typeof removeCart;
}>;
