/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.4.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/browser";
import type * as addCart from "../addCart";
import type * as getCart from "../getCart";
import type * as getItems from "../getItems";
import type * as removeCart from "../removeCart";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  addCart: typeof addCart;
  getCart: typeof getCart;
  getItems: typeof getItems;
  removeCart: typeof removeCart;
}>;
